### ISSUE TITLE
Fix installing dependency phase.

### ISSUE THREAD

**Issue by hemanth** [hemanth/generator-pwa#3]
```
$ cd /tmp; mkdir kk; cd $_; yo pwa
```
```
I'm all done. Running npm install & bower install for you to install the required dependencies. If this fails, try running the command yourself.


npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/kk/package.json'
npm WARN kk No description
npm WARN kk No repository field.
npm WARN kk No README data
npm WARN kk No license field.
bower ENOENT        No bower.json present
```

//cc @gokulkrishh We must turn off bower install and fix the `package.json`

**Comment by tuxredux** [comment]
```bash
I'm all done. Running npm install & bower install for you to install the required dependencies. If this fails, try running the command yourself.


Unhandled rejection Error: Argument #2: Expected string but got null osenv@^0.1.4 fetched in 78ms
    at addDependency (/home/user/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /home/user/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/install/deps.js:463:5
    at /home/user/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /home/user/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/home/user/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/home/user/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/home/user/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/home/user/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /home/user/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /home/user/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/home/user/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/home/user/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/user/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/user/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-06-02T05_28_05_817Z-debug.log
bower                           ENOENT No bower.json present
```
